
TUNING =
{
	IS_DEBUG = true,
	ASSET_QUALITY = ASSET_QUALITY.DEFAULT,

	HUGULA_TONGUE_DEFAULT = 1.0,
	HUGULA_TONGUE_LONG = 2.0,
	HUGULA_TONGUE_LONG_TIME = 10,

	DEFAULT_CHEW_TIME = 1,
}

